"""drop the UNIQUE constraint on crypto_payments.np_payment_id

It guarded nothing: IPN callbacks are looked up by order_id (unique, and
generated by us, one per invoice) and double-crediting is prevented by
credited_at. What it did do was raise IntegrityError inside the IPN handler on
any collision — a 500, which NOWPayments treats as a delivery failure and
retries indefinitely, so one duplicate payment id would produce a permanent
retry loop against a callback that could never succeed.

Replaced with a plain index; the column stays useful for tracing a payment
back to the NOWPayments dashboard.

Revision ID: l7g8h9i0j1k2
Revises: k6f7g8h9i0j1
Create Date: 2026-08-24
"""
from alembic import op

revision = 'l7g8h9i0j1k2'
down_revision = 'k6f7g8h9i0j1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Postgres auto-named the constraint when the column was declared unique.
    op.drop_constraint('crypto_payments_np_payment_id_key', 'crypto_payments', type_='unique')
    op.create_index('ix_crypto_payments_np_payment_id', 'crypto_payments', ['np_payment_id'])


def downgrade() -> None:
    op.drop_index('ix_crypto_payments_np_payment_id', table_name='crypto_payments')
    op.create_unique_constraint('crypto_payments_np_payment_id_key', 'crypto_payments', ['np_payment_id'])
